--must connect to another database (like postgres) first to create db
--psql -U your_user -d postgres
--DROP DATABASE IF EXISTS order_tracking;
CREATE DATABASE order_tracking;
--after creating db
psql -U your_user -d postgres
--DROP SCHEMA IF EXISTS odts CASCADE;
CREATE ROLE odts_admin WITH LOGIN PASSWORD 'admin123';
--
CREATE SCHEMA odts AUTHORIZATION odts_admin;
--
GRANT CONNECT ON DATABASE order_tracking TO odts_admin;
GRANT USAGE, CREATE ON SCHEMA odts TO odts_admin;
--
ALTER DEFAULT PRIVILEGES IN SCHEMA odts
GRANT ALL ON TABLES TO odts_admin;
--

SELECT rolname, rolsuper
FROM pg_roles;

ALTER SCHEMA odts OWNER TO odts_admin;
GRANT CREATE ON DATABASE order_tracking TO odts_admin;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-------------------------
set search_path = odts;

CREATE TABLE IF NOT EXISTS "users" (
	"user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_role_id" INTEGER NOT NULL,
	"dealer_id" INTEGER,
	"user_login_name" VARCHAR(50) NOT NULL,
	"password_hash" TEXT NOT NULL,
	"user_name" VARCHAR(255),
	"user_phone" VARCHAR(20) UNIQUE,
	"user_email" VARCHAR(255),
	-- user is not active is like soft delete
	"user_is_active_flag" BOOLEAN NOT NULL DEFAULT true,
	-- user is locked after incorrect password attempts
	"user_is_locked_flag" BOOLEAN NOT NULL DEFAULT false,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("user_id")
);

COMMENT ON TABLE "users" IS 'Authentication: users login into the application. ';
COMMENT ON COLUMN "users"."user_is_active_flag" IS 'user is not active is like soft delete';
COMMENT ON COLUMN "users"."user_is_locked_flag" IS 'user is locked after incorrect password attempts';


CREATE TABLE IF NOT EXISTS "user_roles" (
	"role_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"role_name" VARCHAR(255) NOT NULL UNIQUE,
	"role_desc" TEXT,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("role_id")
);

COMMENT ON TABLE "user_roles" IS 'user roles';


CREATE TABLE IF NOT EXISTS "dealers" (
	"dealer_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- not for login, Its for reporting, invoicing
	"dealer_code" VARCHAR(50) NOT NULL UNIQUE,
	"dealer_name" VARCHAR(255),
	"dealer_company_name" VARCHAR(255) NOT NULL,
	"dealer_phone" VARCHAR(20),
	"dealer_email" VARCHAR(255),
	"dealer_address" TEXT,
	"dealer_daily_limit" INTEGER,
	"dealer_monthly_target" INTEGER,
	"dealer_is_active_flag" BOOLEAN NOT NULL DEFAULT TRUE,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("dealer_id")
);

COMMENT ON TABLE "dealers" IS 'Master Entity, 
One Dealer → can have one user , one to one relations';
COMMENT ON COLUMN "dealers"."dealer_code" IS 'not for login, Its for reporting, invoicing';


CREATE TABLE IF NOT EXISTS "products" (
	"product_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"product_name" VARCHAR(255) NOT NULL UNIQUE,
	"product_desc" TEXT,
	"product_is_active_flag" BOOLEAN NOT NULL,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("product_id")
);

COMMENT ON TABLE "products" IS 'Master Entity';


CREATE TABLE IF NOT EXISTS "locations" (
	"location_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"location_name" VARCHAR(255) NOT NULL UNIQUE,
	"location_desc" TEXT,
	"location_is_active_flag" BOOLEAN NOT NULL,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("location_id")
);

COMMENT ON TABLE "locations" IS 'Master Entity';


CREATE TABLE IF NOT EXISTS "dealer_orders" (
	"order_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"dealer_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"source_location_id" INTEGER NOT NULL,
	"order_quantity" INTEGER NOT NULL CHECK(order_quantity > 0),
	"order_date" TIMESTAMP NOT NULL,
	"order_status" VARCHAR(255) NOT NULL,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("order_id")
);

COMMENT ON TABLE "dealer_orders" IS 'Transaction Entity';


CREATE TABLE IF NOT EXISTS "order_dispatch" (
	"dispatch_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"order_id" INTEGER NOT NULL,
	"driver_id" INTEGER NOT NULL,
	"dispatch_vehicle_number" VARCHAR(255),
	"builty_number" VARCHAR(255),
	"dispatch_receipt" TEXT,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("dispatch_id")
);

COMMENT ON TABLE "order_dispatch" IS 'Transaction Entity';


CREATE TABLE IF NOT EXISTS "user_login_audit" (
	"login_audit_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"login_user_id" INTEGER NOT NULL,
	-- password or otp
	"login_method" VARCHAR(255),
	"login_status" VARCHAR(255),
	"login_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"logout_at" TIMESTAMP,
	"login_ip_address" VARCHAR(255),
	"login_is_active" BOOLEAN DEFAULT false,
	PRIMARY KEY("login_audit_id")
);


COMMENT ON COLUMN "user_login_audit"."login_method" IS 'password or otp';


CREATE TABLE IF NOT EXISTS "dealer_party" (
	"party_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"dealer_code" VARCHAR(255) NOT NULL,
	"party_code" VARCHAR(255) NOT NULL,
	"party_company_name" VARCHAR(255),
	"party_name" VARCHAR(255),
	"party_address" TEXT,
	"party_phone" VARCHAR(255),
	"party_email" VARCHAR(255),
	"party_is_active_flag" BOOLEAN DEFAULT true,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("party_id")
);



ALTER TABLE "users"
ADD FOREIGN KEY("user_role_id") REFERENCES "user_roles"("role_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "dealer_orders"
ADD FOREIGN KEY("dealer_id") REFERENCES "dealers"("dealer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dealer_orders"
ADD FOREIGN KEY("product_id") REFERENCES "products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dealer_orders"
ADD FOREIGN KEY("source_location_id") REFERENCES "locations"("location_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("dealer_id") REFERENCES "dealers"("dealer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_login_audit"
ADD FOREIGN KEY("login_user_id") REFERENCES "users"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dealer_party"
ADD FOREIGN KEY("dealer_code") REFERENCES "dealers"("dealer_code")
ON UPDATE NO ACTION ON DELETE NO ACTION;

SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'odts'
  AND table_name = 'users';